import type { LucideIcon } from 'lucide-react';
import {
  AlertTriangle, ArrowLeftRight, Banknote, BarChart3, Boxes, CalendarClock, ChartPie, Coins,
  CreditCard, FileSpreadsheet, FileText, Gauge, Landmark, Layers, ListTree, Package2,
  PackageCheck, PackageSearch, Percent, PiggyBank, Scale, ShoppingCart, Store, TrendingDown,
  TrendingUp, Truck, UserRound, Users, Wallet, Warehouse,
} from 'lucide-react';

/**
 * Per-report metadata. Descriptions power the shell header and sidebar search;
 * icons give every report a distinct visual identity; isPointInTime marks
 * stock-snapshot reports (no date-range filter); tags extend search beyond
 * the label (synonyms, accounting terms).
 */

export const reportIcons: Record<string, LucideIcon> = {
  // purchase
  'purchase-register': ShoppingCart,
  'purchase-summary': FileSpreadsheet,
  'purchase-order': FileText,
  'supplier-purchase': Truck,
  'material-purchase': Layers,
  'purchase-category': ChartPie,
  'purchase-cost': Coins,
  'purchase-trend': TrendingUp,
  'purchase-comparison': Scale,
  'supplier-outstanding': Warehouse,
  'supplier-ledger': ListTree,
  // sales
  'sales-register': Store,
  'sales-summary': FileSpreadsheet,
  'product-sales': Package2,
  'sales-trend': TrendingUp,
  'product-sales-analysis': BarChart3,
  'customer-outstanding': UserRound,
  'customer-ledger': ListTree,
  'sales-comparison': Scale,
  'profit-by-product': PiggyBank,
  // processing
  'processing-dispatch': Truck,
  'processing-receive': PackageCheck,
  'pending-pcs': CalendarClock,
  'processor-billing': CreditCard,
  'processor-ledger': ListTree,
  'processing-charges': Banknote,
  'processing-efficiency': Gauge,
  'processing-loss': TrendingDown,
  'processor-performance': Users,
  // inventory
  'current-stock': Boxes,
  'stock-movement': ArrowLeftRight,
  'material-stock': PackageSearch,
  'finished-stock': PackageCheck,
  'low-stock': AlertTriangle,
  'out-of-stock': Package2,
  'inventory-valuation': Coins,
  'lot-history': ListTree,
  'inventory-aging': CalendarClock,
  'inventory-turnover': Percent,
  'stock-adjustment': FileText,
  'stock-ledger': ListTree,
  // financial
  'general-ledger': ListTree,
  'cashbook': Wallet,
  'bank-book': Landmark,
  'trial-balance': Scale,
  'profit-loss': ChartPie,
  'balance-sheet': Landmark,
  'account-summary': FileText,
  'receivable-aging': CalendarClock,
  'payable-aging': CalendarClock,
  'expense-analysis': TrendingDown,
  'revenue-analysis': TrendingUp,
};

export const reportDescriptions: Record<string, string> = {
  'purchase-register': 'Purchases recorded by supplier, material, quantity, and amount.',
  'purchase-summary': 'Purchase totals by supplier with weight and value.',
  'purchase-order': 'Purchase orders by material, weight, and rate.',
  'supplier-purchase': 'Purchase volume and value broken down per supplier.',
  'material-purchase': 'Purchase volume and value broken down per raw material.',
  'purchase-category': 'Purchase value aggregated by material category.',
  'purchase-cost': 'Rate variance analysis: actual cost vs estimated cost per material.',
  'purchase-trend': 'Purchase activity over time, by day.',
  'purchase-comparison': 'Current vs previous period purchases with growth per material.',
  'supplier-outstanding': 'Payable balances per supplier (Cr) and advances (Dr).',
  'supplier-ledger': 'Net Dr/Cr movement per supplier account for the period.',
  'sales-register': 'Sales recorded by customer, product, quantity, and revenue.',
  'sales-summary': 'Sales totals by customer with transaction counts.',
  'product-sales': 'Revenue and volume per product.',
  'sales-trend': 'Revenue over time, by day.',
  'product-sales-analysis': 'Price variance and per-product revenue concentration.',
  'customer-outstanding': 'Receivable balances per customer (Dr) and credits (Cr).',
  'customer-ledger': 'Net Dr/Cr movement per customer account for the period.',
  'sales-comparison': 'Current vs previous period revenue with growth per product.',
  'profit-by-product': 'Estimated profit and margin per product.',
  'processing-dispatch': 'Material dispatched to processors and its current stage.',
  'processing-receive': 'Material received back from processors, linked to dispatches.',
  'pending-pcs': 'Dispatches with pieces still pending at processors.',
  'processor-billing': 'Receipts billed to processors with bill status.',
  'processor-ledger': 'Net Dr/Cr movement per processor account for the period.',
  'processing-charges': 'Processing charges per processor with average per piece.',
  'processing-efficiency': 'Received vs sent efficiency and turnaround per processor.',
  'processing-loss': 'Explicitly recorded loss and wastage per processor and stage.',
  'processor-performance': 'Volume, value, and job count per processor.',
  'current-stock': 'Current quantities and values across your inventory.',
  'stock-movement': 'Stock movements by batch with direction (IN/OUT/ADJUST).',
  'material-stock': 'Raw material stock levels vs minimum levels.',
  'finished-stock': 'Finished goods stock on hand.',
  'low-stock': 'Materials at or below their minimum stock level.',
  'out-of-stock': 'Items with zero or negative stock.',
  'inventory-valuation': 'Estimated value of stock on hand, by item.',
  'lot-history': 'Movement history for each lot/batch.',
  'inventory-aging': 'Batch age and remaining pieces in the pipeline.',
  'inventory-turnover': 'Turnover ratio per product based on outflow vs stock.',
  'stock-adjustment': 'Stock adjustment entries with reasons.',
  'stock-ledger': 'Batch-level ledger: IN/OUT/ADJUST entries with running net change.',
  'general-ledger': 'Detailed account movements and running balances.',
  'cashbook': 'Cash in and out through cash accounts with closing balance.',
  'bank-book': 'Receipts and payments through bank accounts.',
  'trial-balance': 'All account debit/credit balances — must total equal.',
  'profit-loss': 'Revenue minus costs for the period (statement view).',
  'balance-sheet': 'Assets, liabilities, and equity as of a date (statement view).',
  'account-summary': 'Per-account balances with drill-down to vouchers.',
  'receivable-aging': 'Customer balances bucketed by age (0-30/31-60/61-90/90+).',
  'payable-aging': 'Supplier balances bucketed by age (0-30/31-60/61-90/90+).',
  'expense-analysis': 'Expense accounts ranked by amount with % of total.',
  'revenue-analysis': 'Revenue streams ranked by amount with % of total.',
};

export const pointInTimeReports = new Set<string>([
  'current-stock', 'material-stock', 'finished-stock', 'low-stock', 'out-of-stock',
  'inventory-valuation', 'inventory-aging', 'inventory-turnover', 'pending-pcs',
  'balance-sheet',
]);

export const reportTags: Record<string, string[]> = {
  'purchase-register': ['purchases', 'buying', 'grn'],
  'supplier-outstanding': ['payable', 'ap', 'creditors', 'owe'],
  'customer-outstanding': ['receivable', 'ar', 'debtors', 'owe us'],
  'general-ledger': ['gl', 'accounts', 'ledger'],
  'profit-loss': ['p&l', 'income statement', 'pl'],
  'balance-sheet': ['financial position', 'statement'],
  'cashbook': ['cash', 'daily cash'],
  'trial-balance': ['tb', 'audit', 'balancing'],
  'pending-pcs': ['wip', 'at processor', 'pending'],
  'low-stock': ['reorder', 'minimum'],
  'inventory-valuation': ['stock value', 'worth'],
  'receivable-aging': ['aging', 'buckets', 'ar'],
  'payable-aging': ['aging', 'buckets', 'ap'],
  'profit-by-product': ['margin', 'profitability'],
};
